PostHub/Controllers/HomePageController.cs
using Microsoft.AspNetCore.Mvc;
using PostHub.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PostHub.Controllers
{
    public class HomePageController : Controller
    {
        private readonly IPostManager postManager;

        public HomePageController(IPostManager manager)
        {
            postManager = manager;
        }

        public IActionResult Index()
        {
            return View(postManager.GetAllPosts());
        }

        [HttpGet]
        public IActionResult CreatePost()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreatePost(PostModel post)
        {
            postManager.PublishPost(post);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult RemovePost(int id)
        {
            var post = postManager.GetPost(id);
            return View();
        }

        [HttpPost]
        public IActionResult RemovePostConfirmation(int id)
        {
            postManager.RemovePost(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditPost(int id)
        {
            var post = postManager.GetPost(id);
            return View(post);
        }

        [HttpPost]
        public IActionResult EditPost(PostModel post)
        {
            postManager.EditPost(post);
            return RedirectToAction("Index");
        }

        public IActionResult PostView(int id)
        {
            var post = postManager.GetPost(id);
            return RedirectToAction("DisplayPost", "ViewPost", post);
        }

    }
}

PostHub/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PostHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="HomePage" asp-action="Index">PostHub</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HomePage" asp-action="Index">Home</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-center">
        <div class="container">
            &copy; 2023 - PostHub - <a href="https://github.com/mattkmnk">Kamiński Mateusz</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PostHub/Views/Shared/_LayoutWithItems.cshtml
@using Microsoft.AspNetCore.Identity
@using PostHub.Areas.Identity.Data;
@inject SignInManager<PostHubUser> SignInManager
@inject UserManager<PostHubUser> UserManager

<!DOCTYPE html>
<html lang="en" class="h-100 w-100">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PostHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        .bg-gradient-body {
            background: rgb(255,255,255);
            background: linear-gradient(180deg, rgba(255,255,255,1) 0%, rgba(213,249,213,1) 84%, rgba(162,241,162,1) 100%);
        }
    </style>
</head>
<body class="h-100 text-dark bg-gradient-body">
    <div class="page-container">
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom text-dark mb-3 bg-gradient-b">
                <div class="container">
                    <a class="navbar-brand text-dark" asp-area="" asp-controller="HomePage" asp-action="Index">PostHub</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <a class="navbar-nav text-dark" asp-area="" asp-controller="HomePage" asp-action="CreatePost">New Post</a>
                            }
                        </ul>
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </nav>
        </header>
        <div class="container w-50 text-light">
            <main role="main" class="pb-3 h-100 text-dark">
                @RenderBody()
            </main>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>